[cmake]
version = "3.25"
cmkr-include = "cmkr.cmake"


[project]
name = "GotoSlnx"
languages = ["C", "CXX"]
msvc-runtime = "static"
cmake-before = """
set(VCPKG_TARGET_TRIPLET "x64-windows-static" CACHE STRING "" FORCE)
set(VCPKG_LIBRARY_LINKAGE "static" CACHE STRING "" FORCE)
set(VCPKG_CRT_LINKAGE "static" CACHE STRING "" FORCE)
"""

[variables]
VCPKG_TARGET_TRIPLET = "x64-windows-static"
VCPKG_LIBRARY_LINKAGE = "static"
VCPKG_CRT_LINKAGE = "static"

[vcpkg]
version = "2026.01.16"
packages = ["fmt", "tinyxml2", "cxxopts"]


[target.goto-slnx.properties]
CXX_STANDARD = 20
CXX_STANDARD_REQUIRED = true

[find-package.fmt]
config = true
required = true

[find-package.tinyxml2]
config = true
required = true

[find-package.cxxopts]
config = true
required = true

[target.goto-slnx]
type = "executable"
msvc-runtime = "static"
sources = ["src/main.cpp"]
link-libraries = ["fmt::fmt", "tinyxml2::tinyxml2", "cxxopts::cxxopts"]
compile-definitions = ["$<$<CXX_COMPILER_ID:MSVC>:_CRT_SECURE_NO_WARNINGS>"]
